SYMBOLS_CONFIG = {
    "EURUSD": {
        "ema_fast": 21,
        "ema_slow": 50,
        "atr_period": 14,
        "rsi_period": 14,
        "volatility_filter_threshold": 1.2,
    },
    "GBPUSD": {
        "ema_fast": 22,
        "ema_slow": 50,
        "atr_period": 14,
        "rsi_period": 14,
        "volatility_filter_threshold": 1.25,
    },
    "USDJPY": {
        "ema_fast": 20,
        "ema_slow": 50,
        "atr_period": 14,
        "rsi_period": 14,
        "volatility_filter_threshold": 1.1,
    },
    "XAUUSD": {
        "ema_fast": 21,
        "ema_slow": 50,
        "atr_period": 14,
        "rsi_period": 14,
        "volatility_filter_threshold": 1.5,
    },
    "US30": {
        "ema_fast": 21,
        "ema_slow": 50,
        "atr_period": 14,
        "rsi_period": 14,
        "volatility_filter_threshold": 1.6,
    },
    "NDX100": {
        "ema_fast": 20,
        "ema_slow": 50,
        "atr_period": 14,
        "rsi_period": 14,
        "volatility_filter_threshold": 1.55,
    },
    "AUDCAD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "AUDCHF": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "AUDJPY": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "AUDNZD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "CADJPY": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "CHFJPY": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "EURAUD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "EURCAD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "EURCHF": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "EURGBP": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "EURJPY": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "GBPAUD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "GBPJPY": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "NZDUSD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "USDCAD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "USDCHF": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "GER30": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "UK100": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "SPX500": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "XAGUSD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "AUDUSD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "BTCUSD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 2.0},
    "ETHUSD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 2.0},
    "EURNZD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "GBPNZD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "GBPCAD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "NZDCAD": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "CADCHF": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "NZDCHF": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.2},
    "USDZAR": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 2.0},
    "USDMXN": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 2.0},
    "USDNOK": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "USDSEK": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "EURNOK": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "EURSEK": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "JP225": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "HK50": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "STOXX50E": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "USOIL": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.8},
    "UKOIL": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.8},
    "COPPER": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "COCOA": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "SUGAR": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
    "COFFEE": {"ema_fast": 20, "ema_slow": 50, "atr_period": 14, "rsi_period": 14, "volatility_filter_threshold": 1.5},
}
